import { NextResponse } from 'next/server';

// This route simply redirects to the Google OAuth URL generated by url-route.ts
// It expects a userId and optional state in the query string

export async function GET(req: Request) {
  const { searchParams, origin } = new URL(req.url as string);
  const userId = searchParams.get('userId');
  const state = searchParams.get('state');

  if (!userId) {
    return NextResponse.json({ error: 'Missing userId' }, { status: 400 });
  }

  // Forward to the url-route to get the Google OAuth URL
  const urlRes = await fetch(`${origin}/api/google-calendar/url?userId=${encodeURIComponent(userId)}${state ? `&state=${encodeURIComponent(state)}` : ''}`);
  const { url } = await urlRes.json();

  // Redirect the user to the Google OAuth URL
  return NextResponse.redirect(url);
}
